### ISSUE TITLE
Global helpers defined outside of gem's `require_paths`

### ISSUE THREAD

**Issue by riyengar8** [fractaledmind/actionset#59]
When I try to use the latest release (v9.2) of this gem, I get an error when I hit calls in the gem code to one of the globally defined helpers (`flatten_keys_of`):

```
undefined method `flatten_keys_of' for #<ActionSet::FilterInstructions:0x00007fd67693eeb0>
NoMethodError (undefined method `flatten_keys_of' for #<ActionSet::FilterInstructions:0x00007fd67693eeb0>):
  
actionset (0.9.2) lib/action_set/filter_instructions.rb:21:in `get'
actionset (0.9.2) lib/action_set.rb:28:in `filter_set'
actionset (0.9.2) lib/action_set.rb:23:in `process_set'
...
```

Interestingly, this problem disappears when I point my Gemfile to a copy of the gem on my local disk using the `path:` key in the Gemfile.

I'm not entirely sure why this is happening. My LOAD_PATH has `/gems/actionset-0.9.2/lib` on it, and I am requiring `action_set`, which should in turn require `active_set`, which should in turn require `helpers/flatten_keys_of`. All of that is available on the LOAD_PATH.

One other piece of data, here is some console output:

```
modv-ve703-04053:cvpf rgi$ be rails c
Loading development environment (Rails 5.1.7)
irb(main):001:0>  $LOAD_PATH.select { |x| x.include? 'actionset' }
=> ["/Users/rgi/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/actionset-0.9.2/lib"]
irb(main):002:0> flatten_keys_of
NameError: undefined local variable or method `flatten_keys_of' for main:Object
	from (irb):2
irb(main):003:0> 
irb(main):004:0* 
irb(main):005:0* require 'action_set'
=> false
irb(main):006:0> flatten_keys_of
NameError: undefined local variable or method `flatten_keys_of' for main:Object
	from (irb):6
irb(main):007:0> require 'active_set'
=> false
irb(main):008:0> flatten_keys_of
NameError: undefined local variable or method `flatten_keys_of' for main:Object
	from (irb):8
irb(main):009:0> require 'helpers/flatten_keys_of'
=> true
irb(main):010:0> flatten_keys_of
ArgumentError: wrong number of arguments (given 0, expected 1..3)
	from (irb):10
```

What you can see here is that my app on startup is successfully requiring 'action_set' and  'active_set' (note that those require statements return false, indicating that those files were already processed). But the `flatten_keys_of` method is not in scope until I explicitly require 'helpers/flatten_keys_of' (which is found on the LOAD_PATH).

**Comment by riyengar8** [comment]
I think I understand what is going on here. I believe the problem is that the `require 'active_set'` directive in `lib/action_set.rb` is not finding the `lib/active_set.rb` file. So none of the requires in that file are happening. If I change that to `require_relative './active_set'`, things work as expected.

**Comment by riyengar8** [comment]
One final aha moment. My Gemfile still had actionset in it as a separate entry. So, when actionset was getting required, it was the older version that did not have the helper in scope.

I'm closing this issue.
